### ISSUE TITLE
miktex.portable: checksum failure

### ISSUE THREAD

**Issue by koppor** [aronovgj/choco-auto#17]
```
miktex.portable package files install completed. Performing other installation steps.
Ftp-ing miktex.portable
  from 'ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/systems/win32/miktex/setup/miktex-portable.exe'
Progress: 100% - Completed a total of 189192237 bytes of C:\Users\koppor\AppData\Local\Temp\chocolatey\miktex.portable\2.9.5987\miktex.portableInstall.zip
Download of miktex.portableInstall.zip (180.43 MB) completed.
Error - hashes do not match. Actual value was 'CC7D67F481E009E5EECE8B531B9A86C1F47C7DD107CF8BC36B7EE1689C5B3811'.
ERROR: Checksum for 'C:\Users\koppor\AppData\Local\Temp\chocolatey\miktex.portable\2.9.5987\miktex.portableInstall.zip' did not meet 'b6773ba988007a88c361f63d27833e63fefdb8011238f0ca843135a3c4ffded9' for checksum type 'sha256'. Consider passing --ignore-checksums if necessary.
The install of miktex.portable was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\miktex.portable\tools\chocolateyInstall.ps1'.
```

I tried it multiple times for different servers (https://mirror.unicorncloud.org, ftp://ftp.fu-berlin.de/, ftp://ftp.rrzn.uni-hannover.de). Maybe the author replaced the binary file?

Can the package be updated? The most recent release is from yesterday (11/15/2016; http://www.miktex.org/download)

**Comment by aronovgj** [comment]
Yes, that happened because of the new version. Each time a new version is released, my PC has to be running in order to automatically push a new package. 

In general there are two solutions:
1. The current one, where the link in the install script is this:
   http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe
   That means if the package is outdated, you can always force-upgrade the software to the newest version if you just ignore the checksums.
2. The link would be 
   http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable-2.9.6161.exe
   The package would never break (I think) but you could not upgrade to a newer version of the software, unless a new package version is pushed to chocolatey.org.

Which one would you prefer? I like to be up-to-date, so I chose the first solution.

Also, as I just turned on my PC, the new package was automatically pushed.

**Comment by koppor** [comment]
I would prefer the second option, because this is consistent with other
tools. Further, there is the miktex update manager, which also updates
miktex itself. So, I recommend to pin miktex.

**Comment by aronovgj** [comment]
Pinning packages is not the responsibility of the package. 

I'll give the link-thing some thought.

**Comment by espoelstra** [comment]
@aronovgj I think the second option is more consistent with other packages like Java (jre8 and server-jre8). This also allows downgrading to a prior version if somebody has an issue with the latest version. You can easily set up an AppVeyor job to make updating to new package versions much easier, I'm currently working on making a Chocolatey app template AppVeyor.yml for nvm-windows and server-jre. I agree you shouldn't pin a version in the virtual package, but having explicit versions called out in the actual .install/.portable package is very handy for business use.

Also if you use the example of server-jre, the original maintainer did a great job of taking the version from the nuspec file and parsing it out to automatically update the download URL, so you can basically maintain new versions by just tweaking the nuspec file via the GitHub web UI.

**Comment by aronovgj** [comment]
Why would I need to parse link versions in my install script? That would already be done in Ketarin so that the new scripts have the complete download link on each push. If you want to copy out the link from the install script and paste it into your browser, you won't have to replace manually `$majorVersion`, `$minorVersion` and so on.

Also chocolatey.org is explicitly not for business use:
https://chocolatey.org/docs/community-packages-disclaimer

Anyway, I'll change the miktex packages to have version-specific download links. Let's hope that will work out well, as I am not sure whether I decided to make it work the way it works now due to issues with CTAN.

**Comment by espoelstra** [comment]
Ahh, I hadn't noticed that you were using Ketarin. I haven't had much experience with it, though I know recently the Chocolatey team has been moving to AU for their packages, but I think that's a work in progress.

I realize that Chocolatey actively warns users not to use it in business environments, but reading that page carefully it's basically a large CYA (cover your behind) that encourages business users to upgrade to their paid version. Ironically the Business version uses the same feed, the only difference is that the Chocolatey business license enables users to pull from a "private" CDN where they are caching the downloads that the packages reference. The business version also supports automatically downloading from the CDN and putting the package on an internal storage mechanism, but otherwise unless a business is going to invest in the time to rewrite all the installers (highly unlikely), most places will be using the installers as written (and hopefully contributing back improvements).

Either way, putting hard links to mirrors.ctan.org with explicit versions will definitely increase the reliability, and you could possibly even trigger an AppVeyor job on a schedule to detect a new version and build a new release so you wouldn't have to leave your machine running constantly.

**Comment by aronovgj** [comment]
The business version mostly is about trust. For example each package is scanned for viruses before each install, whereas for the free repo they are only scanned periodically.

Anyway, versions are now explicit, starting with next package version.
