### ISSUE TITLE
Installing geforce-game-ready-driver removes geforce experience

### ISSUE THREAD

**Issue by aronovgj** [aronovgj/choco-auto#8]
Probably because before installing the GFExperience folder is removed.

@Link-Satonaka any idea?

**Comment by AeliusSaionji** [comment]
This is very surprising, I'll take a look later

**Comment by aronovgj** [comment]
@Link-Satonaka ping

**Comment by AeliusSaionji** [comment]
I observed this happening and all I can say is: nvidia can be dumb  ¯\_(ツ)_/¯
If you think anyone at nvidia will care, you can try to report this to them.

There are several options.
1. Implement arguments for the chocolatey script, where the user must specify they want/don't-want GeForce Experience. We should probably do this anyway so that users can strip out 3dvision, too.
2. We do nothing. Half the point of GeForce Experience is to manage the nvidia drivers. Users should either use GeForce Experience instead of this package, or this package instead of GeForce Experience.
3. Make another package which doesn't exclude GeForce Experience

**Comment by aronovgj** [comment]
https://github.com/aronovgj/choco-auto/commit/ceba96ccd540d99c077c549dab2d9a0769dc5a9e

**Comment by aronovgj** [comment]
I decided to leave it in because:
- Installing Geforce Experience is default behavior (so is installing the other crapware, but that does not do whats in the next point)
- Packages should not touch other software

> Implement arguments for the chocolatey script, where the user must specify they want/don't-want GeForce Experience. 

That should be done next...

> Half the point of GeForce Experience is to manage the nvidia drivers.

Yes, but that is only half of the point.
